[files]
extend-exclude = [
    "website/client/.vitepress/config/*.ts",
    "website/client/src/**/*.md",
    ".git",
    "browser/**/*.txt",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Viá»‡t Nam",
]

[default.extend-words]
# "styl" is the file extension for Stylus CSS preprocessor
styl = "styl"
